sudo docker stop backend
sudo docker stop mysql
sudo docker stop video2plate
sudo docker stop plate2char
sudo docker stop IPCam_Controller
sudo docker rm backend
sudo docker rm mysql
sudo docker rm video2plate
sudo docker rm plate2char
sudo docker rm IPCam_Controller