# Generated by Django 4.2.1 on 2023-05-28 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPCamera',
            fields=[
                ('Source', models.CharField(default='', max_length=150, primary_key=True, serialize=False)),
                ('Entrance_Code', models.CharField(default='', max_length=5)),
                ('Entrance_Name', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
